"""Type stub for the compiled ``cognivore._native`` pybind11 extension
(built from ``native/bindings.cpp`` / ``native/vector_index.cpp``).

Hand-written because pybind11 extensions don't ship their own stubs and
stubgen output for them is typically unreadable; this is small enough to
maintain by hand and keep in sync with ``native/bindings.cpp``.
"""

class SearchResult:
    id: int
    score: float

class FlatIndex:
    def __init__(self, dim: int) -> None: ...
    def add(self, id: int, vector: list[float]) -> None: ...
    def search(self, query: list[float], k: int) -> list[SearchResult]: ...
    def __len__(self) -> int: ...
    @property
    def dim(self) -> int: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(blob: bytes) -> FlatIndex: ...

class NSWIndex:
    def __init__(self, dim: int, m: int = ..., ef_construction: int = ...) -> None: ...
    def add(self, id: int, vector: list[float]) -> None: ...
    def search(self, query: list[float], k: int, ef: int = ...) -> list[SearchResult]: ...
    def __len__(self) -> int: ...
    @property
    def dim(self) -> int: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(blob: bytes) -> NSWIndex: ...
